// 1. LOS OBJETOS LITERALES, SON UNA ESTRUCTURA DE DATOS QUE TAMBIEN SON CONOCIDOS
// COMO ARREGLOS ASOCIATIVOS O MAPAS

// 2. OBJETOS LITERALES !== DE LOS OBJETOS DE POO(PROGRAMACION ORIENTADA A OBJETOS)

// 3. OBJETOS LITERALES !== JSON

// 4. PUEDEN ALMACENAR CUALQUIER TIPO DE DATO, DESDE PRIMITIVOS HASTA REFERENCIAS

// 5. LOS OBJ. LITERALES SON UN OBJETO DE TIPO "Object"

const miCuentaDeAlumno = {
  // LAS PROPIEDADES SE DEFINEN COMO PARES DE CLAVE Y VALOR
  id: "45ghj34g54h3g",
  nombre: "Cinthya",
  materias: ["Español", "Matematicas", "Fisica"],
  mostrarGrupo() {
    return `El alumno ${this.nombre}, se encuentra cursando la materia ${this.materias[2]}`;
  }
};

// "this", ES UN OBJETO, QUE SE CREA PARA CADA FUNCION, CON EXCEPCION DE LAS ARROW FUNCTIONS Y TAMBIEN EXISTE PARA CADA OBJETO,
// YA SEA OBJETO LITERAL O DE POO Y REPRESENTA UNA AUTOREFERENCIA PARA PODER ACCEDER A MIS PROPIAS PROPIEDADES
console.log(miCuentaDeAlumno);

// PODEMOS ACCEDER A LOS VALORES DE NUESTRAS PROPIEDADES Y METODOS, USANDO LA NOTACION DE PUNTO (DOT NOTATION)

console.log(miCuentaDeAlumno.materias[1]);
console.log(miCuentaDeAlumno.mostrarGrupo());
