// 1. LA FUNCION FLECHA, NOS DA UNA SINTAXIS MAS LIMPIA Y FACIL DE LEER
// 2. NORMALMENTE, SE ALMACENAN EN CONSTANTES O EN VARIABLES.
// 3. EN LAS FUNCIONES FLECHA, NO EXISTE EL OBJETO "this", ESTAS NO PUEDEN SER PROTOTIPOS

let saludar = () => {
  return "Hola Mundo";
};

console.log(saludar());

// SHORT ARROW FUNCTIONS// FUNCIONES CORTAS DE FLECHA
// REGLAS DE SINTAXIS EN ARROW FUNCTIONS:
// * SI MI FUNCION SOLO RETORNA UN VALOR, PUEDO QUITAR EL RETURN EXPLICITO,
// LAS LLAVES Y HACER USO DEL RETURN IMPLICITO
const suma = (a, b) => a + b;
console.log(suma(4, 9));

// SHORT ARROW FUNCTION QUE PIDE UN SOLO PARAMETRO
// REGLAS DE SINTAXIS EN ARROW FUNCTIONS:
// * SI MI FUNCION SOLO RETORNA UN VALOR Y PIDE UN SOLO PARAMETRO, PUEDO APLICAR LA REGLA ANTERIOR Y ADEMAS, QUITAR LOS PARENTESIS DEL PARAMETRO
const saludar2 = persona => "Hola " + persona;
console.log(saludar2("Cinthya"));